

export interface Client {
    id?: string; // Optional, since Supabase can auto-generate it
    username?: string;
    email: string  ;
    password: string;
    photoprofile?: string | null;
    created_at?: string; // Optional, auto-generated by Supabase
}
